alter table OMEGA_ORGANISATION add constraint FK_OMEGA_ORGANISATION_ON_COUNTRY foreign key (COUNTRY_ID) references OMEGA_COUNTRY(ID);
alter table OMEGA_ORGANISATION add constraint FK_OMEGA_ORGANISATION_ON_INDUSTRY foreign key (INDUSTRY_ID) references OMEGA_INDUSTRY(ID);
create index IDX_OMEGA_ORGANISATION_ON_COUNTRY on OMEGA_ORGANISATION (COUNTRY_ID);
create index IDX_OMEGA_ORGANISATION_ON_INDUSTRY on OMEGA_ORGANISATION (INDUSTRY_ID);
