alter table OMEGA_BOOKING add constraint FK_OMEGA_BOOKING_ORGANISATION foreign key (ORGANISATION_ID) references OMEGA_ORGANISATION(ID);
alter table OMEGA_BOOKING add constraint FK_OMEGA_BOOKING_SHOW foreign key (SHOW_ID) references OMEGA_SHOW(ID);
alter table OMEGA_BOOKING add constraint FK_OMEGA_BOOKING_SRT_CONTACT foreign key (SRT_CONTACT_ID) references OMEGA_CONTACT(ID);
alter table OMEGA_BOOKING add constraint FK_OMEGA_BOOKING_ORG_CONTACT foreign key (ORG_CONTACT_ID) references OMEGA_CONTACT(ID);
create index IDX_OMEGA_BOOKING_ORGANISATION on OMEGA_BOOKING (ORGANISATION_ID);
create index IDX_OMEGA_BOOKING_SHOW on OMEGA_BOOKING (SHOW_ID);
create index IDX_OMEGA_BOOKING_SRT_CONTACT on OMEGA_BOOKING (SRT_CONTACT_ID);
create index IDX_OMEGA_BOOKING_ORG_CONTACT on OMEGA_BOOKING (ORG_CONTACT_ID);
